ajax/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

widget/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class University(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Student(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    date_birth = models.DateField()
    residencce = models.CharField(max_length=200)
    photo = models.ImageField(blank=True)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    intro = models.TextField()

widget/forms.py
# core/forms.py

from django import forms
from .models import University, Student
from .widgets import CounterTextInput, AutoCompleteWidget, starWidget


class UniversityForm(forms.ModelForm):
    class Meta:
        model = University
        fields = ['name']
        widgets = {
            'name': CounterTextInput,
        }


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        widgets = {
            'university': AutoCompleteWidget,
            'grade': starWidget,
        }

widget/views.py
from django.shortcuts import render

# Create your views here.

widget/templates/widget/autocomplete_select.html
{% include "django/forms/widgets/select.html" %}

{{ form.media }}

<script>
    $(function(){
        $('#{{ widget.attrs.id }}').select2();
    })
</script>

widget/templates/widget/counter_text.html
<!-- templates/widgets/counter_text.html -->

{% include "django/forms/widgets/input.html" %}

<span id="counter_{{ widget.attrs.id }}"></span>

<script>
    document.querySelector('#{{widget.attrs.id}}').addEventListener("input", function () {
        document.querySelector("#counter_{{ widget.attrs.id}}").innerHTML = this.value.length + '글자';
    })
</script>

widget/templates/widget/star_rate.html
{% load static %}

{% include "django/forms/widgets/input.html" %}


<!-- <link rel="stylesheet" href="{% static 'widget/rateit/rateit.css' %}">
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script src="{% static 'widget/rateit/jquery.rateit.min.js' %}" ></script> -->

{{ form.media }}

<input type="rating" name="grade" value="4" required="" id="id_grade" min="0" max="5" step="1" style="display: none;">

<div id="star_id_grade" class="rateit rateit-bg" data-rateit-backingfld="#id_grade">
    <!-- 생략 -->
</div>